### ISSUE TITLE
Unusual behaviour: increasing `minseglen` causes smaller segments

### ISSUE THREAD

**Issue by multimeric** [rkillick/EnvCpt#11]
I seem to have encountered a strange scenario for `EnvCpt`. I have attached the associated dataset as a CSV file:

[test_data.csv](https://github.com/rkillick/EnvCpt/files/6806066/test_data.csv)
```R
dat = readr::read_lines('test_data.csv') %>% as.numeric 
```

Now, if we plot it with `minseglen=23`, we get a very poorly fit model with only 5 changepoints. It's hard to see from the yellow plot colour (would be lovely if I could change that, by the way!), but the latter 3/4 of the model is one diagonal trendline, which visually doesn't really fit the model well at all.
```R
dat %>%
  EnvCpt::envcpt(models="trendcpt", minseglen=23) %>%
  plot
```
![image](https://user-images.githubusercontent.com/5019367/125394684-65d2cc00-e3ed-11eb-977d-6f6da7ebaaa6.png)

However, if I *increase* the `minseglen` to 24, which should actually make the model less likely to make splits, then the model fixes itself and produces 13 changepoints:
```R
dat %>%
  EnvCpt::envcpt(models="trendcpt", minseglen=24) %>%
  plot
```
![image](https://user-images.githubusercontent.com/5019367/125394730-78e59c00-e3ed-11eb-937f-c50097fcf855.png)

This behaviour is very counterintuitive. I think the second case is correct, and fits quite well, but for some reason as soon as we go below `minseglen=24`, the algorithm seems to get confused.

**Comment by multimeric** [comment]
Actually it seems that this is, somewhat obviously, caused by having a response variable that is quantized ie an integer. I'm still not sure if this is the correct behaviour of `EnvCpt`, but it was fairly trivial for me to remove the bug in my code that was converting this column to an integer, and it resulted in perfectly normal behaviour.

**Comment by rkillick** [comment]
Thanks for getting in touch with your experience.  The assumption of the model is a Normal error distribution.  If the response can only take integer values then this violates that assumption.  If there is enough variability in the data then this often isn't a problem. However, if you get runs of the same value then this produces a 0 variance estimate which is problematic and results in poor fits.  An easy way to get around this is to jitter the data first as this adds a small amount of noise to the data which removes the 0 variance problem.

For this type of data, you may want to look at replacing the trend cost function with a model that has changes followed by exponential increase/decrease.  This will avoid getting several changes on the exponential part of the curve and should capture the 4 larger changes with a more realistic fit.

**Comment by multimeric** [comment]
Very helpful explanation, thank you.

For your latter suggestion, is this possible within `EnvCpt`? Or do you mean that I should e.g. log transform the data and then fit it as normal?

**Comment by rkillick** [comment]
You could take logs and fit the trend model to the logs as a first approximation.

The exponential growth/decay cost function isn't available in EnvCpt ----- yet.  This package is the closest to what you might need that is available at the moment AFAIK [SpikeTrain](https://github.com/jewellsean/FastLZeroSpikeInference).  It would need modification for your problem though as they assumed a positive spike and decay model.  The alternative is to code a cost function for the exponential growth/decay model (maybe using existing R packages) and then input this as a cost function in the PELT C (or commented out R) code from the changepoint package.  It may not be efficient from a coding perspective but it would do the job.

**Comment by multimeric** [comment]
Many thanks, I'll have a look into those options.
