### ISSUE TITLE
data with x and y axis

### ISSUE THREAD

**Issue by Lisa051992** [rkillick/EnvCpt#13]
I have data which are no time series, but where each data point has a x and y information. Is there a chance to model this data as well? (I found in the manual that one can specify only a vector or time series for envcpt (x). What I would actually need to specify is a dataframe with x and y column or a y~x function).

Thanks a lot in advance!

**Comment by rkillick** [comment]
Sorry I have taken a long time to reply to this, the notification must have gotten lost in my inbox.  Apologies.

Yes, you can use covariates but you will need to use the inner function EnvCpt:::cpt.reg() and specify the data in the first argument as a matrix, with the first column as y, then the remaining columns as the covariates, including a column of 1's for the intercept.  There is no automatic parsing of the columns as you expect with use of lm().
